### ISSUE TITLE
Post request hangs and no HTTP response is returned when invalid user/password entered with basic auth enabled

### ISSUE THREAD

**Issue by richardschoen** [sitemule/ILEusion#19]
If an invalid user and password is entered, it appears that the HTTP POST request hangs and no response is returned if a bad user/pass combo entered. The following error is thrown in the app server joblog: "ProfileHandle is not valid.", however nothing is returned. The app server should return a valid response of some sort even if the user/password login fails rather than hanging. 

To recreate the issue, try sending a request with an invalid user/password combination in the basic auth header.

**Comment by WorksOfLiam** [comment]
Fixed in commit 10e9c33e748a349f4dfca3948fa486d44054ddcf.

Will now return an error with the error code / CPF if login is not successful.
