### ISSUE TITLE
Allow CL command calls to return CPF message reponse list so messages can be used 

### ISSUE THREAD

**Issue by richardschoen** [sitemule/ILEusion#20]
This is not a bug but a functionality request. 

On the CL command response, send back the CPF messages generated from the call so that the caller can utilize the CPF messages. Ex command: CHKOBJ command will send back nothing if an object exists, but throws an escape message with a valid CPF ID and message in failure. 

You can use JT400 CL command calls as a guide for this functionality.

**Comment by WorksOfLiam** [comment]
I will be switching out `QCMDEXC` for `SYSTEM`, which will let me access `_EXCP_MSGID` for the error code to be passed back to the frontend.

https://www.ibm.com/support/knowledgecenter/en/ssw_ibm_i_72/rtref/system.htm

**Comment by WorksOfLiam** [comment]
![image](https://user-images.githubusercontent.com/3708366/50085509-2cfcf700-01f2-11e9-91f6-183d3e7f3330.png)

**Comment by WorksOfLiam** [comment]
Fixed in 83a91d71a4b1bdc14a781097e8d3b53814a85e2b.

The `code` attribute is returned if there is an error code available.
